TAMULib/fw-registry

bibReferenceLinks/extractors/bibReferenceLinksAMDB.json, bibReferenceLinks/extractors/bibReferenceLinksMSDB.json, bibReferenceLinks/extractors/sql/bibReferenceLinksAMDB.sql, bibReferenceLinks/extractors/sql/bibReferenceLinksMSDB.sql
=> Item 4: Bibliographic Extractor SQL Queries (bib reference links)

holdings/referenceData/0_institutionLocationUnits.json, holdings/referenceData/1_campusLocationUnits.json, holdings/referenceData/2_libraryLocationUnits.json, holdings/referenceData/3_servicePoints.json, holdings/referenceData/4_locations.json, holdings/referenceData/callNumberTypes.json
=> Holdings reference data

items/referenceData/0_statisticalCodeTypes.json, items/referenceData/1_statisticalCodes.json, items/referenceData/loanTypes.json
resolves #12 
resolves #13 
resolves #14
=> Items reference data

bibs/extractors/bibsAMDB.json, bibs/extractors/bibsMSDB.json, bibs/extractors/sql/bibsAMDB.sql, bibs/extractors/sql/bibsMSDB.sql
=> Item 4: Bibliographic Extractor SQL Queries (bibs)

users/extractors/sql/patronsAMDB.sql, users/extractors/sql/patronsDistinctMSDB.sql, users/tasks/js/processFlatData.js
Resolves #17 
- Moves phone number data from address level to patron level in extractor sql
- Processes phone number data for folio representation
No other data seemed to be missing.
=> [17]  User Migration should include all missing properties

holdings/extractors/holdingsAMDB.json, holdings/extractors/holdingsMSDB.json, holdings/extractors/sql/holdingsAMDB.sql, holdings/extractors/sql/holdingsMSDB.sql
=> [Sprint6-15] holdings extractor sql holdings

items/extractors/itemsAMDB.json, items/extractors/itemsMSDB.json, items/extractors/sql/itemsAMDB.sql, items/extractors/sql/itemsMSDB.sql
This discludes all items that have multiple bib_ids.
Only items with a single bib_id are returned by these queries.
resolves #16
=> [Sprint6-16] Create Items Extractor SQL Query

bibs/workflow.json, holdings/workflow.json, inventoryReferenceLinks/workflow.json, items/workflow.json, userReferenceLinks/workflow.json, users/workflow.json, vendorReferenceLinks/workflow.json, vendors/workflow.json
=> Add requires authentication to workflows

bibs/extractors/sql/bibsAMDB.sql, bibs/extractors/sql/bibsMSDB.sql, bibs/tasks/enhanceBibsInstanceReferenceLinksAMDB.json, bibs/tasks/enhanceBibsInstanceReferenceLinksMSDB.json, bibs/tasks/enhanceBibsSourceRecordReferenceLinksAMDB.json, bibs/tasks/enhanceBibsSourceRecordReferenceLinksMSDB.json, bibs/tasks/js/processConvertMarc.js, bibs/tasks/js/processFinalizeData.js, bibs/workflow.json, inventoryReferenceLinks/tasks/js/processInventoryReferenceLinks.js
=> Bib workflow tasks

bibs/referenceData/identifierTypes.json, holdings/referenceData/4_locations.json, instance_mapping_rules.json
- add identifier types to bib reference data
- update instance mapping rules back to tamu custom
- update locations reference data
=> Update reference data

README.md
Follow up to fix #124 , updating the readme to reflect the changes introduced by #128 .
=> [Issue 124] Update readme to reflect changes.

README.md, e-resource/nodes/start.json, e-resource/triggers/startTrigger.json, gobi/nodes/start.json, gobi/triggers/startTrigger.json, orcid/nodes/start.json, orcid/triggers/startTrigger.json, purchase-orders/nodes/start.json, purchase-orders/triggers/startTrigger.json
Also, updated start event expression paths and readme.
=> Issue 135: GOBI scheduled start by cron

medsci-gps-zone/nodes/start.json, medsci-gps-zone/triggers/startTrigger.json
The trigger file is missing.
There is a typo where the "d" is missing from `medsci-gps-zone`.
=> Issue 101: Add missing start trigger and fix typo.

purchase-orders/nodes/js/prepareHoldings.js
=> Removed duplicate access info

shelflist-items/nodes/js/buildShelflistQuery.js
- Resolves #234 
This changes the location search from permanent to effective, as per the customer's request.
=> issue-shelflist-location 234

purchase-orders/nodes/js/prepareSourceRecord.js
The MARC JSON string does not parse correctly when passing to Java utility method
=> [Issue 245] purchase order properly pass marc JSON to java from script delegate

purchase-orders/nodes/js/prepareSourceRecord.js
Add missing instance hrid to externalIdsHolder.
=> Add instance hrid to source record external id holder

README.md, circ-fines/nodes/delete.json, coral-extract/nodes/loadHoldingsTemplate.json, coral-extract/nodes/loadInstanceTemplate.json, gobi/nodes/deleteGzippedReport.json, gobi/nodes/deleteReport.json, medsci-gps-zone/nodes/delete.json, orcid/nodes/fastDeleteTsv.json, orcid/nodes/studentDeleteTsv.json, rapid-electronic-monos/nodes/deleteRapidPrintMonosTSV.json, rapid-print-monos/nodes/deleteRapidPrintMonosTSV.json, rapid-print-serials/nodes/deleteRapidPrintSerialsTSV.json, shelflist-holdings/nodes/deleteReportFile.json, shelflist-items/nodes/deleteReportFile.json
=> Added tenantId to the delete processes

purchase-orders/nodes/js/buildCompositePurchaseOrder.js, purchase-orders/nodes/js/extractFieldsFromMarcRecord.js, rapid-electronic-monos/nodes/gzipRapidPrintMonosTSV.json, rapid-electronic-serials/nodes/gzipRapidElectronicSerialsTSV.json, rapid-print-monos/nodes/gzipRapidPrintMonosTSV.json, rapid-print-serials/nodes/gzipRapidPrintSerialsTSV.json
=> Sprint staging

shelflist-items/nodes/js/buildShelflistQuery.js
=> SILW is now generating unique results

shelflist-items/nodes/js/buildShelflistQuery.js
=> Sprint9 staging

README.md
The README was overlooked when adding PR #311.
=> Issue 308: Add missing README.md documentation for nbs-items-note workflow.

circ-fines/nodes/start.json, coral-extract/nodes/start.json, gobi/nodes/start.json, item-history-update/nodes/start.json, patron/nodes/start.json, rapid-electronic-monos/nodes/start.json, rapid-electronic-serials/nodes/start.json, rapid-print-monos/nodes/start.json, rapid-print-serials/nodes/start.json
Resolves #315 
- Tested timezone for UTC vs local and found it needed to be converted to UTC.
- Adjusted local time to UTC for scheduled cron jobs.
=> Issue 315 Review and fix Workflow "cronjobs" to be consistent in regards to UTC and local time.

create-notes/nodes/js/processInputVariables.js
Follow up to #316 .
Relies on: [TAMULib/mod-camunda/pull/227](https://github.com/TAMULib/mod-camunda/pull/227).
Future improvements to sanitization may be performed in mod-camunda.
=> Issue 316: Implement SQL escape support via FormatUtility in mod-camunda.

README.md
resolves issue #318 
Fixed the asymmetrical use of single quotes in curl requests.
=> Issue 318: Fixed the asymmetrical use of single quotes in curl requests

create-notes/nodes/connectToLDP.json, create-notes/nodes/js/buildSuccessEmail.js, create-notes/nodes/js/processInputVariables.js, create-notes/nodes/js/processItem.js
=> 316 continuation of create notes

README.md
Also fix some grammatical issues.
=> Update the README regarding variable substitution to be more correct.

README.md, shelflist-items/nodes/sendReportEmail.json
PRS:
- #382 
- #384 
- #385
- #386
=> Sprint19 staging

README.md, purchase-orders/nodes/js/extractInstanceIdFromPoLine.js, purchase-orders/nodes/js/prepareInstance.js
This represents all of the fw-registry changes related to the investigation and hotfixing of the issue #397.
- #398
- #399
=> Investigation 2024 12 02 staging

purchase-orders/nodes/js/prepareItem.js
=> Print book items now have initial status

README.md, gobi/nodes/connect.json, gobi/nodes/disconnect.json, gobi/nodes/query.json
=> Refactored GOBI workflow

README.md, shelflist-holdings/nodes/connect.json, shelflist-holdings/nodes/disconnect.json, shelflist-holdings/nodes/js/buildShelflistQuery.js, shelflist-holdings/nodes/queryShelfList.json
=> Shelflist holdings query refactored to work with MetaDB
